name: Build and Push Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: jdag05
          password: Jesusdavid5*
       
      - name: Debug environment
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is set."
          else
          echo "DOCKER_USERNAME is not set."
          fi

      - name: Build and push container
        run: |
          docker build -t my-container .
          docker tag my-container jdag05/assignment6:prod
          docker push jdag05/assignment6:prod
